<?xml version="1.0" encoding="utf-8"?><Database Name="dulyDB" Class="DulyDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MY-SURFACEPRO3\SQLEXPRESS;Initial Catalog=dulyDB;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dulyDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="NChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="displayName" Type="System.String" DbType="NChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="createdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="lastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserActivations" Member="UserActivations">
    <Type Name="UserActivation">
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="activationCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>